---
- name: Install base package Arch Linux
  sudo: yes
  pacman:
    name: "{{ xfce_base_pkg }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Archlinux"

- name: Install extra package Arch Linux
  sudo: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ xfce_xfwm4_themes_pkg }}"
    - "{{ xfce_numix_themes_pkg }}"
  when: xfce_extra_pkg == true and ansible_os_family == "Archlinux"
