---
- name: Install base package Debian/Ubuntu
  sudo: yes
  apt:
    name: "{{ xfce_base_pkg }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Install extra package Debian/Ubuntu
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ xfce_xfwm4_themes_pkg }}"
    - "{{ xfce_numix_themes_pkg }}"
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
