---
- name: Install base package CentOS/Fedora/SuSe
  sudo: yes
  yum:
    name: "{{ xfce_base_pkg }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "CentOS" or ansible_os_family == "Fedora" or ansible_os_family == "SuSe"

- name: Install extra package CentOS/Fedora/SuSe
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ xfce_xfwm4_themes_pkg }}"
    - "{{ xfce_numix_themes_pkg }}"
  when: xfce_extra_pkg == true and ansible_os_family == "CentOS" or ansible_os_family == "Fedora" or ansible_os_family == "SuSe"
