---
- name: Ensure .config/xfce4/terminal dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/xfce4/terminal"
    state: directory
    recurse: yes

- name: Copy xfce terminalrc file
  template:
    src: ../../templates/common/xfce4-terminalrc.j2
    dest: "{{ ansible_env.HOME }}/.config/xfce4/terminal/terminalrc"
    mode: 0644
